/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hoadon;

import java.io.*;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
//import java.util.Vector;

/**
 *
 * @author DELL
 */
public class HOADONFORM extends javax.swing.JDialog {

    /**
     * Creates new form HOADONFORM
     */
    private List<String> dsMua =  new Vector<>();
    public HOADONFORM() {
        initComponents();
        option = 0;
    }
    public HOADONFORM(String tenNV, String maHD, List<String> list, LocalDateTime thoiGianXuat,long tongTien) {
        initComponents();
        String temp,s1[];
        this.inTenNV.setText(tenNV);
        this.inMaHD.setText(maHD);
        temp = thoiGianXuat.format(DateTimeFormatter.ofPattern("d/MMM/uuuu HH:mm:ss"));
        this.inTG.setText(temp);
        temp = String.valueOf(tongTien);
        this.inTongTien.setText(temp + " vnđ");
        
        DefaultTableModel model = new DefaultTableModel();
        String a[] = {"       STT", "   Mã Sách", "  Tên Sách", "  Số Lượng", "   Giá Tiền"};
        model.setColumnIdentifiers(a);
        
        ArrayList arrRows = new ArrayList();
        int j = 0;
        this.dsMua = list;
        for(String i : list) {            
            s1 = i.split("-");
            arrRows.add(String.valueOf(j+1));
            arrRows.add(String.valueOf(s1[0]));
            arrRows.add(String.valueOf(s1[1]));
            arrRows.add(String.valueOf(s1[7]));
            arrRows.add(String.valueOf(s1[4]));
            model.addRow(arrRows.toArray());
            arrRows.clear();
            j++;
        }
        
        this.DSMuaHang.setModel(model);
        option = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        DSMuaHang = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        TenNV = new javax.swing.JLabel();
        TGXuat = new javax.swing.JLabel();
        MHD = new javax.swing.JLabel();
        inTG = new javax.swing.JLabel();
        inTenNV = new javax.swing.JLabel();
        inMaHD = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        TC = new javax.swing.JLabel();
        inTongTien = new javax.swing.JLabel();
        btn_Finish = new javax.swing.JButton();
        btn_Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Bill");
        setAlwaysOnTop(true);

        DSMuaHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "", null, null, null},
                {"2", null, null, null, null},
                {"3", null, null, null, null},
                {"4", null, null, null, null},
                {"5", null, null, null, null},
                {"6", null, null, null, null},
                {"7", null, null, null, null},
                {"8", null, null, null, null},
                {"9", null, null, null, null},
                {"10", null, null, null, null},
                {"11", null, null, null, null},
                {"12", null, null, null, null},
                {"13", null, null, null, null},
                {"14", null, null, null, null},
                {"15", null, null, null, null},
                {"16", null, null, null, null},
                {"17", null, null, null, null},
                {"18", null, null, null, null},
                {"19", null, null, null, null},
                {"20", null, null, null, null},
                {"21", null, null, null, null},
                {"22", null, null, null, null},
                {"23", "", null, null, null},
                {"24", null, null, null, null},
                {"25", null, null, null, null}
            },
            new String [] {
                "STT", "Mã Sách", "               Tên Sách", "Số Lượng", "   Giá Tiền"
            }
        ));
        jScrollPane2.setViewportView(DSMuaHang);
        if (DSMuaHang.getColumnModel().getColumnCount() > 0) {
            DSMuaHang.getColumnModel().getColumn(0).setPreferredWidth(5);
            DSMuaHang.getColumnModel().getColumn(1).setPreferredWidth(30);
            DSMuaHang.getColumnModel().getColumn(2).setPreferredWidth(150);
            DSMuaHang.getColumnModel().getColumn(3).setPreferredWidth(30);
            DSMuaHang.getColumnModel().getColumn(4).setPreferredWidth(50);
        }

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TenNV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TenNV.setText("Tên Nhân Viên:");

        TGXuat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TGXuat.setText("Thời gian xuất:");

        MHD.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        MHD.setText("Mã Hóa Đơn:");

        inTG.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        inTenNV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(MHD, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TGXuat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inTenNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inTG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MHD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TGXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inTG, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TC.setText("Tổng cộng:");

        inTongTien.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btn_Finish.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_Finish.setText("Xuất");
        btn_Finish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_FinishMouseClicked(evt);
            }
        });

        btn_Back.setText("Quay lại");
        btn_Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_BackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(289, Short.MAX_VALUE)
                .addComponent(TC, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_Finish)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Back))
                    .addComponent(inTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TC, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Finish)
                    .addComponent(btn_Back))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_FinishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_FinishMouseClicked
        // TODO add your handling code here:
        HoaDon hd = new HoaDon();
        kesach.Ke ke = new kesach.Ke();
        List<String> ds = hd.leakDS();
        try {
            hd.ghiFileIDHoaDon(this.getMAHD());
        } catch (IOException ex) {
            Logger.getLogger(HOADONFORM.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        try {
            this.ghiFileHoaDon();
        } catch (IOException ex) {
            Logger.getLogger(HOADONFORM.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            this.ghiFileSach(ds);
        } catch (IOException ex) {
            Logger.getLogger(HOADONFORM.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ke.capNhap(dsMua);
        } catch (IOException ex) {
            Logger.getLogger(HOADONFORM.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
        option = 1;
    }//GEN-LAST:event_btn_FinishMouseClicked

    private void btn_BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BackMouseClicked
        // TODO add your handling code here:
        option = -1;
        this.dispose();
    }//GEN-LAST:event_btn_BackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HOADONFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HOADONFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HOADONFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HOADONFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HOADONFORM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DSMuaHang;
    private javax.swing.JLabel MHD;
    private javax.swing.JLabel TC;
    private javax.swing.JLabel TGXuat;
    private javax.swing.JLabel TenNV;
    private javax.swing.JButton btn_Back;
    private javax.swing.JButton btn_Finish;
    private javax.swing.JLabel inMaHD;
    private javax.swing.JLabel inTG;
    private javax.swing.JLabel inTenNV;
    private javax.swing.JLabel inTongTien;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
    private int option;
    //********************************************************************************setter and getter
    public void setTenNV(String ten){
        this.inTenNV.setText(ten);
    }
    public void setMAHD(String id){
        this.inMaHD.setText(id);
    }
    public void setTGX(LocalDateTime thoiGianXuat){
        String temp = thoiGianXuat.format(DateTimeFormatter.ofPattern("d/MMM/uuuu HH:mm:ss"));
    }
    public void setTongTien(long tien){
        String temp = String.valueOf(tien);
        this.inTongTien.setText(temp + " vnđ");
    }
    public void setlist(List<String> list){
        this.DSMuaHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"         1", null, null, null, null},
                {"         2", null, null, null, null},
                {"         3", null, null, null, null},
                {"         4", null, null, null, null},
                {"         5", null, null, null, null},
                {"         6", null, null, null, null},
                {"         7", null, null, null, null},
                {"         8", null, null, null, null},
                {"         9", null, null, null, null},
                {"         10", null, null, null, null},
                {"         11", null, null, null, null},
                {"         12", null, null, null, null},
                {"         13", null, null, null, null},
                {"         14", null, null, null, null},
                {"         15", null, null, null, null},
                {"         16", null, null, null, null},
                {"         17", null, null, null, null},
                {"         18", null, null, null, null},
                {"         19", null, null, null, null},
                {"         20", null, null, null, null},
                {"         21", null, null, null, null},
                {"         22", null, null, null, null},
                {"         23", null, null, null, null},
                {"         24", null, null, null, null},
                {"         25", null, null, null, null}
            },
            new String [] {
                "       STT", "   Mã Sách", "  Tên Sách", "  Số Lượng", "   Giá Tiền"
            }
        ));
    }
    public void setDSMua(List<String> list){
        this.dsMua = list;
    }
    public String getTenNV(){
        return this.inTenNV.getText();
    }
    public String getMAHD(){
        return this.inMaHD.getText();
    }
    public String getTongTien(){
        return this.inTongTien.getText();
    }
    public String getTG(){
        return this.inTG.getText();
    }
    public List<String> getDSMua(){
        return dsMua;
    }
    
    //****************************************************************************cac ham xu ly
    public List<Integer> soLuongSach(List<String> list){
        int soLuong = 0;
        ArrayList<Integer> arrSL = new ArrayList<>();
        for(String i : list){
            for(String j : list){
                if(i == j){
                    soLuong++;
                }
            } 
            arrSL.add(soLuong);
            soLuong = 0;
        }
        return arrSL;
    }
//    public List<String> editListDS(List<String> list){
//        for(int i = 0;i < list.size();i++){
//            for(int j = i+1;j < list.size();j++){
//                if(list.get(i) == list.get(j)){
//                    list.remove(j);
//                }
//            }
//        }
//        return list;
//    }
//    public List<Integer> editArrSL(List<String> list,List<Integer> arrRows){
//        for(int i = 0;i < list.size();i++){
//            for(int j = i+1;j < list.size();j++){
//                if(list.get(i) == list.get(j)){
//                    arrRows.remove(j);
//                    list.remove(j);
//                }
//            }
//        }
//        return arrRows;
//    }
    public void ghiFileSach( List<String> ds) throws IOException {
        File file = new File("Sach.txt");
        FileWriter writer = new FileWriter(file);
        BufferedWriter buf = new BufferedWriter(writer);
        List<String> dsMua = this.getDSMua();
        List<String> dsBanDau = ds;
        List<String> dsLucSau =   new ArrayList<String>();
        String addLucSau;
        for (String temp:dsBanDau){
            for(String temp1:dsMua){
                addLucSau = "";
                if(temp.split("-")[0].equals(temp1.split("-")[0])){
                    String str[] = temp1.split("-");
                    int soLuong = Integer.parseInt(str[6]) - Integer.parseInt(str[7]);
                    str[6] = Integer.toString(soLuong);
                    for(int i =0; i<6;i++){
                        addLucSau += str[i]+"-";
                    }
                    addLucSau += str[6];
                    dsLucSau.add(addLucSau);
                }
                else{
                    dsLucSau.add(temp);
                }
            }
        }
         List<String> list = new ArrayList<String>();
         for(String element:dsLucSau){
             if(!list.contains(element)){
                 list.add(element);
             }
         }
         for(int i = 0;i < list.size()-1;i++){
             if(list.get(i).split("-")[0].equals(list.get(i+1).split("-")[0]) ){
                 if(Integer.parseInt(list.get(i).split("-")[6]) < Integer.parseInt(list.get(i+1).split("-")[6])){
                     list.remove(i+1);
                 }
                 else{
                     list.remove(i);
                 }
             }
         }
        for(String temp:list){
            buf.write(temp+"\n");
        }
        buf.close();
        writer.close();
    }
    
    public  void ghiFileHoaDon()throws IOException{
        File file = new File("HoaDon.txt"); 
        OutputStream outputStream = new FileOutputStream(file,true);
        OutputStreamWriter outputStreamWriter = new OutputStreamWriter(outputStream);
        List<String> dsMua = this.getDSMua();
        // Dùng để xuống hàng        
        outputStreamWriter.write(this.getMAHD());
        outputStreamWriter.write("-");
        outputStreamWriter.write(this.getTenNV());
        outputStreamWriter.write("-");
        outputStreamWriter.write(this.getTG());
        outputStreamWriter.write("-");
        outputStreamWriter.write(this.getTongTien());
        outputStreamWriter.write("\n");
        for(String i : dsMua){
            outputStreamWriter.write(i);
            outputStreamWriter.write("\n");
        }
        
        outputStreamWriter.write("-------------------------------------------------------------------------------------");
        outputStreamWriter.write("\n");
        
        // Đây là phương thức quan trọng!
        // Nó sẽ bắt chương trình chờ ghi dữ liệu xong thì mới kết thúc chương trình.
        outputStreamWriter.flush();
        outputStream.close();
        outputStreamWriter.close();
    }
    
    public int option(){
        return this.option;
    }
}
