/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
KT số lượng sách
 */
package hoadon;
import static Sach.TimKiem.KTinput;
import java.awt.Component;
import java.time.*;
import java.util.*;
import javax.swing.JOptionPane;
/**
 *
 * @author DELL
 */
public class TaoHD extends javax.swing.JFrame {

//    /**
//     * Creates new form TAOHHD
//     */
    List<String> dsMua;
//    boolean soLuongClick = true;
    int soLuong;
    List<String> dsSachTrongKho;
//    List<Integer> arrSL = null;
    public TaoHD() {
        initComponents();
        dsMua = new Vector<>();
        dsSachTrongKho = new Vector<>();
    }
    public TaoHD(String tenNV, String maHD) {
        initComponents();
        this.inTenNV.setText(tenNV);
        this.inMAHD.setText(maHD);
        dsMua = new Vector<>();
        dsSachTrongKho = new Vector<>();
    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MHD = new javax.swing.JLabel();
        TenNV = new javax.swing.JLabel();
        lb_TimKiem = new javax.swing.JLabel();
        inMAHD = new javax.swing.JLabel();
        inTenNV = new javax.swing.JLabel();
        inputTimKiem = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        LabelThongTin = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dsCacSach = new javax.swing.JList<>();
        btnXuatHD = new javax.swing.JButton();
        btnHuyHD = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        soLuongSach = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Invoice");
        setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        MHD.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        MHD.setText("Mã Hóa Đơn:");

        TenNV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TenNV.setText("Tên Nhân Viên:");

        lb_TimKiem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_TimKiem.setText("Mã sách:");

        inMAHD.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        inputTimKiem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        inputTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputTimKiemKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTimKiemKeyTyped(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Thêm vào hóa đơn");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        LabelThongTin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                        .addGap(648, 648, 648))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TenNV)
                            .addComponent(MHD))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inMAHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inTenNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_TimKiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputTimKiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MHD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inMAHD, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TenNV, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(inTenNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelThongTin)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách hóa đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        dsCacSach.setBackground(new java.awt.Color(204, 204, 204));
        dsCacSach.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        dsCacSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dsCacSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dsCacSach);

        btnXuatHD.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnXuatHD.setText("Xuất Hóa Đơn");
        btnXuatHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXuatHDMouseClicked(evt);
            }
        });

        btnHuyHD.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnHuyHD.setText("Hủy Hóa Đơn");
        btnHuyHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHuyHDMouseClicked(evt);
            }
        });
        btnHuyHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyHDActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Số lượng:");

        soLuongSach.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        soLuongSach.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"0","1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100" }));
        soLuongSach.setEditable(true);
        soLuongSach.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                soLuongSachItemStateChanged(evt);
            }
        });
        soLuongSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soLuongSachActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setText("Xóa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1001, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addComponent(btnXuatHD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHuyHD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(soLuongSach, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(soLuongSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXuatHD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHuyHD))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void dsCacSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsCacSachMouseClicked
        this.soLuongSach.setVisible(true);
        String row = dsCacSach.getSelectedValue();
        String maSach = row.split("-")[0];
        for (String temp:dsMua){
            if(temp.split("-")[0].equals(maSach)){
                int value = Integer.parseInt(temp.split("-")[7]);
                this.soLuongSach.setSelectedItem(value);
                break;
            }
            else
                this.soLuongSach.setSelectedItem(0);
        }
                 
    }//GEN-LAST:event_dsCacSachMouseClicked

    private void btnXuatHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXuatHDMouseClicked
        // TODO add your handling code here:
        int temp = dsMua.size();
        if(dsMua.size()==dsSachTrongKho.size()){
            long tien = updateTongTien(this.dsMua);
            LocalDateTime thoiGianXuat = LocalDateTime.now();
            HoaDon hd = new HoaDon(this.getMAHD(),this.getTenNV(),this.getDSMua(),thoiGianXuat,tien);
            HOADONFORM hdf = new HOADONFORM(hd.getTenNV(),hd.getIDHoaDon(),hd.getListIDSach(),hd.getTGXuat(),tien);
            hdf.setVisible(true);
            if(hdf.option()==1)
                this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Nhập thiếu số lượng!", "Warning!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnXuatHDMouseClicked

    private void btnHuyHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHuyHDMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnHuyHDMouseClicked

    private void soLuongSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soLuongSachActionPerformed
        // TODO add your handling code here:
        this.soLuong = Integer.parseInt(this.soLuongSach.getSelectedItem().toString());    
        if(this.soLuong != 0){
            String temp = dsCacSach.getSelectedValue().toString() +"-"+ Integer.toString(this.soLuong);
            for(int i = 0;i < dsMua.size();i++){
                if(dsMua.get(i).split("-")[0].equals(temp.split("-")[0])){
                    dsMua.remove(i);
                    break;
                }                 
            }
            this.dsMua.add(temp);           
        }
    }//GEN-LAST:event_soLuongSachActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        themDS();
    }//GEN-LAST:event_jButton1MouseClicked

    private void soLuongSachItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_soLuongSachItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_soLuongSachItemStateChanged

    private void inputTimKiemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputTimKiemKeyTyped
        // TODO add your handling code here:
        themDS();
    }//GEN-LAST:event_inputTimKiemKeyTyped

    private void inputTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputTimKiemKeyReleased
        // TODO add your handling code here:
        timKiem();
    }//GEN-LAST:event_inputTimKiemKeyReleased

    private void btnHuyHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyHDActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_btnHuyHDActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String sach = dsCacSach.getSelectedValue();
        dsSachTrongKho.remove(sach);
        for (String s:dsMua){
            if(s.contains(sach)){
                dsMua.remove(s);
                break;
            }
        }
        dsCacSach.setListData((Vector<String>)dsSachTrongKho);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaoHD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaoHD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaoHD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaoHD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TaoHD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelThongTin;
    private javax.swing.JLabel MHD;
    private javax.swing.JLabel TenNV;
    private javax.swing.JButton btnHuyHD;
    private javax.swing.JButton btnXuatHD;
    private javax.swing.JList<String> dsCacSach;
    private javax.swing.JLabel inMAHD;
    private javax.swing.JLabel inTenNV;
    private javax.swing.JTextField inputTimKiem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_TimKiem;
    private javax.swing.JComboBox<String> soLuongSach;
    // End of variables declaration//GEN-END:variables
    
    //********************************************************************************setter and getter
    public void setArrSL(String ten){
        this.inTenNV.setText(ten);
    }
    public void setTenNV(String ten){
        this.inTenNV.setText(ten);
    }
    public void setMAHD(String id){
        this.inMAHD.setText(id);
    }
    public void setlist(List<String> list){
        this.dsCacSach.setListData((Vector<? extends String>) list);
    }
    public String getTenNV(){
        return this.inTenNV.getText();
    }
    public String getMAHD(){
        return this.inMAHD.getText();
    }
    public List<String> getDSMua(){
        return dsMua;
    }
    public List<String> getDSSachTrongKho(){
        return dsSachTrongKho;
    }
    
    //************************************************************************************các hàm xử lý 
    public long updateTongTien(List<String> ds){ 
        long tien = 0;
        for(String item: this.dsMua){      
            tien += Long.parseLong(item.split("-")[4])* Long.parseLong(item.split("-")[7]);                                                                 
        }
        return tien;
    }
    
    public boolean ktDanhSach(String str){
        for(String s : this.dsMua){
            if(s == str){
                return true;
            }
        }        
        return false;
    }
    
    public void themDS(){
        String maSach = inputTimKiem.getText();
        if(maSach.isEmpty())
            LabelThongTin.setText("Khung tìm kiếm đang trống");
        if(!KTinput(maSach))
            JOptionPane.showMessageDialog(rootPane, "Không nhập kí tự đặt biệt", "Cảnh báo", JOptionPane.ERROR_MESSAGE);
        else{
            Sach.Kho kho = new Sach.Kho();
            Sach.Sach sach = kho.timMaSach(maSach);
            if(sach==null)
                LabelThongTin.setText("Mã sách không tồn tại");
            else{
                LabelThongTin.setText(sach.toString());
                dsSachTrongKho.add(sach.toString());
                dsCacSach.setListData((Vector<String>)dsSachTrongKho);
                dsCacSach.setSelectedIndex(dsSachTrongKho.size()-1);
            }
        }
    }
    
    public void timKiem(){
        String maSach = inputTimKiem.getText();
        if(!KTinput(maSach))
            JOptionPane.showMessageDialog(rootPane, "Không nhập kí tự đặt biệt", "Cảnh báo", JOptionPane.ERROR_MESSAGE);
        else{
            Sach.Kho kho = new Sach.Kho();
            Sach.Sach sach = kho.timMaSach(maSach);
            if(sach==null)
                LabelThongTin.setText("Mã sách không tồn tại");
            else{
                LabelThongTin.setText(sach.toString());
            }
        }
    }
}
